### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by jazzdan** [upserve/uppend#35]
It seems like uppend should be able to provide the user with some useful operations metrics. There are two questions to consider here: the method by which we should collect metrics, and the metrics that we want to expose.

When it comes to how to collect metrics there are a couple options:

1. Do what we seem to do now: log metrics to stdout/a file, with a job that collects these and forwards them along to datadog/whatever as applicable.
2. Use an HTTP server and have something else that polls the container for the metrics. I like this method, especially if open source is in this project's future, as it allows anyone to easily see the metrics without grepping logs, or setting up an additional service. This approach is inspired by the `expvar` package in go https://golang.org/pkg/expvar/
3. Use JMX (I don't really know how this works and the benefits over HTTP are unclear to me)

As for useful metrics, these come to mind:

- [ ] Number of open file descriptors
- [ ] Most requested keys, possibly with varying time windows (most requested in last minute, 5 minutes, 15 minutes)
- [ ] Average, p95 and p99 read latency (though precalculating pains me)
- [ ] Average, p95, p99 write latency, broken out by write "type" (blob, index, etc)
- [ ] Average, p95, p99 throughput of storage operations in bytes
- [ ] Number of threads?
- [ ] Connected clients, by IP address
- [ ] Size of various queues, caches
- [ ] Number of keys in the database

**Comment by bfulton** [comment]
Basis for this is added in #43.
